"""
Great Expectations quality block.

Great Expectations is a library, not a long-running service, so this module
adds no container. Instead it ships an Airflow DAG (gx_quality_dag.py) that
runs a GX expectation suite against the lakehouse via Trino, and the GX
library is installed onto the Airflow worker (see services/orchestration/
airflow.py, which adds it to that container's _PIP_ADDITIONAL_REQUIREMENTS
when this quality stack is selected).

The DAG imports great_expectations lazily inside the task body, so only the
worker — which actually executes the task — needs the library; the scheduler
and webserver parse the DAG without it.

Validates: the iceberg.etl.top_customers table produced by iceberg_etl_demo.
"""

from __future__ import annotations

from pathlib import Path


def service_blocks(selections: dict) -> dict:
    # No container — GX runs in-process on the Airflow worker. Writing the DAG
    # is the side effect that wires the quality layer in.
    _write_quality_dag()
    return {}


def _write_quality_dag() -> None:
    d = Path("dags")
    d.mkdir(parents=True, exist_ok=True)
    (d / "gx_quality_dag.py").write_text(_dag_source(), encoding="utf-8", newline="\n")


def _dag_source() -> str:
    return '''"""
gx_quality_dag.py  (auto-generated by the great_expectations quality module)

Runs a Great Expectations suite against iceberg.etl.top_customers (built by the
iceberg_etl_demo DAG) through Trino. The task fails if any expectation fails,
so this gates data quality inside Airflow.

great_expectations is imported lazily inside the task so only the Celery worker
needs the library installed.
"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator


# Trino SQLAlchemy URL — no password (Trino auth is disabled); the catalog is
# "iceberg" and the table lives in schema "etl".
TRINO_CONN = "trino://airflow@trino:8080/iceberg"


def run_expectations():
    import great_expectations as gx
    from great_expectations import expectations as gxe

    ctx = gx.get_context(mode="ephemeral")
    ds = ctx.data_sources.add_sql("trino_ds", connection_string=TRINO_CONN)
    asset = ds.add_table_asset(
        name="top_customers", table_name="top_customers", schema_name="etl"
    )
    batch = asset.add_batch_definition_whole_table("whole")

    suite = ctx.suites.add(gx.ExpectationSuite(name="top_customers_quality"))
    suite.add_expectation(gxe.ExpectTableRowCountToBeBetween(min_value=1))
    suite.add_expectation(gxe.ExpectColumnValuesToNotBeNull(column="custkey"))
    suite.add_expectation(gxe.ExpectColumnValuesToNotBeNull(column="name"))
    suite.add_expectation(
        gxe.ExpectColumnValuesToBeBetween(column="acctbal", min_value=5000)
    )

    validation = ctx.validation_definitions.add(
        gx.ValidationDefinition(name="top_customers_vd", data=batch, suite=suite)
    )
    result = validation.run()

    for r in result.results:
        print(f"  {r.expectation_config.type}: {'PASS' if r.success else 'FAIL'}")
    if not result.success:
        raise ValueError("Great Expectations validation failed — see task log.")
    print("All expectations passed.")


default_args = {
    "owner": "platform",
    "retries": 1,
    "retry_delay": timedelta(minutes=2),
}

with DAG(
    dag_id="gx_quality_checks",
    default_args=default_args,
    description="Validate iceberg.etl.top_customers with Great Expectations",
    schedule=None,  # trigger manually, or after iceberg_etl_demo
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["platform", "quality", "great_expectations"],
) as dag:

    validate = PythonOperator(
        task_id="run_expectations",
        python_callable=run_expectations,
    )
'''


def env_vars(selections: dict) -> dict:
    return {}


def named_volumes(selections: dict) -> list[str]:
    return []


def named_networks(selections: dict) -> list[str]:
    return []
