"""
soda_quality_dag.py  (auto-generated by the soda quality module)

Runs a SodaCL check suite against iceberg.etl.top_customers (built by the
iceberg_etl_demo DAG) through Trino. The task fails if any check fails.

soda is imported lazily inside the task so only the Celery worker needs it.
"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator


SODA_CONFIG = """
data_source trino_ds:
  type: trino
  host: trino
  port: 8080
  username: soda
  catalog: iceberg
  schema: etl
"""

SODA_CHECKS = """
checks for top_customers:
  - row_count > 0
  - missing_count(custkey) = 0
  - min(acctbal) > 5000
"""


def run_soda_scan():
    from soda.scan import Scan

    scan = Scan()
    scan.set_data_source_name("trino_ds")
    scan.add_configuration_yaml_str(SODA_CONFIG)
    scan.add_sodacl_yaml_str(SODA_CHECKS)
    exit_code = scan.execute()
    print(scan.get_logs_text())
    if exit_code != 0:
        raise ValueError(f"Soda scan failed (exit {exit_code}) — see logs above.")
    print("All Soda checks passed.")


default_args = {
    "owner": "platform",
    "retries": 1,
    "retry_delay": timedelta(minutes=2),
}

with DAG(
    dag_id="soda_quality_checks",
    default_args=default_args,
    description="Validate iceberg.etl.top_customers with Soda Core",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["platform", "quality", "soda"],
) as dag:

    scan = PythonOperator(task_id="run_soda_scan", python_callable=run_soda_scan)
